
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#% Configuration Management Data
# 

#% Coding Standard
# TCL
#  
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%  Analysis Dependencies
# 
#
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#  Assumptions and Known Limitations
#
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Description: Generates all vendor information, version data and compilation date of the axi4_id_pkg.vhd file
#
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
proc getinfo {path package_file vendor vendorinfo version} {

   # Completes the vendor name with spaces, rounds it down and converts it to hexadecimal
   set tmp "                ";
   binary scan $vendor$tmp a16 vendor;
   binary scan $vendor H* vendor_hex;
   
   set tmp "                ";
   binary scan $vendorinfo$tmp a16 vendorinfo;
   binary scan $vendorinfo H* vendorinfo_hex;
   
   # Completes the version with spaces, rounds it down and converts it to hexadecimal
   set tmp "                ";
   binary scan $version$tmp a16 version;
   binary scan $version H* version_hex;

   # Gets date and time, convert them to hexadecimal
   set tmp "                ";
   set date_info [ clock format [clock seconds] -format {%y%m%d%H%M} ];
   binary scan $date_info$tmp a16 date_info;
   binary scan $date_info H* date_hex;


   #################################################################################################################################
   ## Displays the obtained data
   #################################################################################################################################
   puts "";
   puts "Package Name   : [file join $path $package_file.vhd]";
   puts "Vendor         : $vendor";
   puts "VendorInfo     : $vendorinfo";
   puts "Version        : $version";
   puts "Date/Time      : $date_info";
   
   return "$date_info $vendor_hex $vendorinfo_hex $version_hex $date_hex"
}

# ##################################################################################################################################
# ## Process to generate the axi4lite_id_pkg.vhd code
# ##################################################################################################################################
proc generate_vhdl {path package_file vendor vendorinfo version date vendor_hex vendorinfo_hex version_hex date_hex   } {
   set comment1 "--==================================================================================================================================";
   
   if { [ catch {
      # Open File
      file delete -force [file join $path "$package_file.vhd"]
      set file_handler [open [file join $path "$package_file.vhd"] w];
      
      # Generates the file content
      puts $file_handler $comment1;
      puts $file_handler "-- $package_file.vhd";
      puts $file_handler $comment1;
      puts $file_handler "-- This file is automatically generated.";
      puts $file_handler "-- DO NOT EDIT.";
      puts $file_handler $comment1;
      
      puts $file_handler "LIBRARY IEEE;\nUSE IEEE.STD_LOGIC_1164.ALL;\n";
      puts $file_handler "PACKAGE $package_file is\n";

      puts $file_handler $comment1;
      puts $file_handler "-- VENDOR : $vendor";
      puts $file_handler $comment1;
      puts $file_handler "CONSTANT id_vendor_c     : STD_ULOGIC_VECTOR(127 DOWNTO 0) := x\"${vendor_hex}\";\n";

      puts $file_handler $comment1;
      puts $file_handler "-- VENDORINFO : $vendorinfo";
      puts $file_handler $comment1;
      puts $file_handler "CONSTANT id_vendorinfo_c : STD_ULOGIC_VECTOR(127 DOWNTO 0) := x\"${vendorinfo_hex}\";\n";
      
      puts $file_handler $comment1;
      puts $file_handler "-- VERSION : $version";
      puts $file_handler $comment1;
      puts $file_handler "CONSTANT id_version_c    : STD_ULOGIC_VECTOR(127 DOWNTO 0) := x\"${version_hex}\";\n";
      
      puts $file_handler $comment1;
      puts $file_handler "-- Compilation Date and Time : $date";
      puts $file_handler $comment1;    
      puts $file_handler "CONSTANT id_date_c       : STD_ULOGIC_VECTOR(127 DOWNTO 0) := x\"${date_hex}\";\n";

      puts $file_handler "END $package_file;";
      
      # Close file
      close $file_handler;
      
   } result ] } {
      return -code error $result;
   } else {
      return 1;
   }
}